CREATE TABLE IF NOT EXISTS artistas(
  id INT AUTO_INCREMENT PRIMARY KEY,
  Artes VARCHAR(255) NOT NULL,
  Epoca VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS galeria(
  id INT AUTO_INCREMENT PRIMARY KEY,
  Excusoes VARCHAR(255) NOT NULL,
  Horarios_de_Funcionamento VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS funcionarios(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  horarios VARCHAR(255) NOT NULL,
  especialidade VARCHAR(255) NOT NULL
);

