"""add artist desc

Revision ID: 354ff0e75a13
Revises: 8fa0c136cc1a
Create Date: 2025-11-19 13:03:02.083992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354ff0e75a13'
down_revision = '8fa0c136cc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resumo', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.drop_column('resumo')

    # ### end Alembic commands ###
