"""Fixing DB

Revision ID: 8fa0c136cc1a
Revises: 
Create Date: 2025-11-19 10:12:10.419429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fa0c136cc1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artista_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('link_image', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('funcionarios')
    op.drop_table('galeria')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galeria',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('artista_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('excursao', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('horario', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dia', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.id'], name=op.f('galeria_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_unicode_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.create_table('funcionarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('horario', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('artista_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artista_id'], ['artistas.id'], name=op.f('funcionarios_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_unicode_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('obras')
    # ### end Alembic commands ###
