"""Add nova coluna

Revision ID: b97a143e528d
Revises: 354ff0e75a13
Create Date: 2025-12-01 15:03:33.430753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97a143e528d'
down_revision = '354ff0e75a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lore_link', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.drop_column('lore_link')

    # ### end Alembic commands ###
