"""Change periodo_atuacao to ano_inicio and ano_fim

Revision ID: c101f14ea95e
Revises: b97a143e528d
Create Date: 2025-12-02 17:25:09.009622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c101f14ea95e'
down_revision = 'b97a143e528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_inicio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ano_fim', sa.Integer(), nullable=True))
        batch_op.drop_column('periodo_atuacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_atuacao', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('ano_fim')
        batch_op.drop_column('ano_inicio')
    # ### end Alembic commands ###
